---
title: "Homework 5"
author: "Elizabeth Fritz"
date: "November 29, 2023"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# packages needed
library("readr")
library("dplyr")
library("lubridate")
library("ggplot2")
library("scales")
library("ggthemes")
library("stringr")
```


```{r}
# reading in homicides data
homicides <- read_csv("data/homicide-data.csv")

# creating city_state and date variables
baltimore_homicides <- homicides %>%
  mutate(city_state = paste(city, state, sep = ", ")) %>%
  filter(city_state == "Baltimore, MD") %>%
  mutate(reported_date = ymd(reported_date),
         reported_month = month(reported_date),
         reported_year = year(reported_date),
         reported_month_year = (paste(reported_month, reported_year, sep = "-")),
         month_year = my(reported_month_year))
```

```{r}
# grouping by month_year to count monthly_homicides
# creating season variable
baltimore_monthly <- baltimore_homicides %>% 
  group_by(month_year) %>% 
  summarize(monthly_homicides = n()) %>% 
  ungroup() %>% 
  mutate(reported_month = month(month_year),
         season = case_when(reported_month %in%
                              c(1:4, 11:12) ~ "Winter",
                            reported_month %in% 
                              c(5:10) ~ "Summer"))

# creating dataframe of Freddie Gray's arrest
freddie_gray <- baltimore_monthly %>% 
  filter(month_year == "2015-04-01")

# creating a histogram of monthly homicides 
plot <- baltimore_monthly %>% 
  arrange(month_year) %>% 
  ggplot() + 
  geom_col(aes(x = month_year, y = monthly_homicides, fill = season)) +
  geom_vline(xintercept = freddie_gray$month_year, 
             color = "red", size = 1, linetype = 2) +
  geom_smooth(span = 0.15, se = FALSE, aes(x = month_year, y = monthly_homicides)) +
  geom_text(aes(x = freddie_gray$month_year, 
                y = freddie_gray$monthly_homicides), 
            label = "Arrest of Freddie Gray") +
  theme_dark() + 
  scale_fill_manual(values = c("lightgray", "lightblue")) +
  ggtitle("Homicides in Baltimore, MD") +
  labs(x = "Date", y = "Monthly homicides") +
  theme(legend.position = "bottom") +
  theme(legend.title = element_blank())

plot
```

